package com.staticnoiselog.springboot3service;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Generated by Spring Initializr.
 * <p>
 * Does not use Testcontainers, which means that you have to start PostgreSQL manually before running this test. This
 * is inconvenient, because even for a <code>./gradlew clean build</code> you have to remember to start PostgreSQL
 * first. Therefore, this test is "@Disabled" and left here only to explain the disadvantages of not using
 * Testcontainers.
 */
@SpringBootTest
@Disabled
class DemoApplicationTests {
    @Test
    void contextLoads() {
    }
}